version: '3.8'
services:
  postgresql:
    image: postgres:13.4
    # volumes:
    #   - ~/volumes/jhipster/flickr2/postgresql/:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=ADMIN
      - POSTGRES_PASSWORD=ADMIN
      - POSTGRES_HOST_AUTH_METHOD=trust
    # If you want to expose these ports outside your dev PC,
    # remove the "127.0.0.1:" prefix
    ports:
      - 127.0.0.1:5432:5432
